-- Trigger nivel superior

GO
CREATE TRIGGER tr_OnServer
ON ALL SERVER 
FOR CREATE_DATABASE -- AQUI DEFINE OQUE DESEJA MONITORAR
AS
	DECLARE @dados XML;
	SET @dados = EVENTDATA(); -- RETORNA TODOS OS DADOS E INFOS DO EVENTO
GO